FROM apache/airflow:2.11.2-python3.12

USER root

# Java e utilitários
RUN apt-get update && apt-get install -y \
    default-jdk wget tar curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Versões
ENV SPARK_VERSION=3.5.2
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=${SPARK_HOME}/bin:${PATH}

# Baixa e instala Spark binário
RUN wget -qO- "https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" \
    | tar -xz -C /opt \
    && mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} \
    && chmod -R a+rX ${SPARK_HOME}

# Instala pyspark compatível e o provider do Airflow
RUN python -m pip install --no-cache-dir pyspark==${SPARK_VERSION} \
    && python -m pip install --no-cache-dir apache-airflow-providers-apache-spark==5.6.0

# Permissões
RUN mkdir -p /home/airflow/.local && chown -R 50000:50000 /home/airflow/.local || true

USER airflow
